-- MySQL Script generated by MySQL Workbench
-- Fri Mar 23 15:28:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/*
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vodagonedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vodagonedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vodagonedb` DEFAULT CHARACTER SET utf8 ;
USE `vodagonedb` ;


*/

-- -----------------------------------------------------
-- Table `vodagonedb`.`User`
-- -----------------------------------------------------
CREATE TABLE `User`(
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profilename` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB DEFAULT CHARSET=latin1; 


-- -----------------------------------------------------
-- Table `vodagonedb`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vodagonedb`.`Subscription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aanbieder` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `prijs` DOUBLE NOT NULL,
  `startDatum` DATE NOT NULL,
  `verdubbeling` VARCHAR(45) NOT NULL,
  `deelbaar` TINYINT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `vodagonedb`.`Abonnees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vodagonedb`.`Abonnees` (
  `idAbonnees` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAbonnees`))
ENGINE = InnoDB DEFAULT CHARSET=latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
